### ISSUE TITLE
Can't  compile with wlroots 0.14.1-1

### ISSUE THREAD

**Issue by paleknight894** [wizbright/waybox#28]
../waybox-0.0.2.1/include/waybox/server.h:20:10: fatal error: wlr/types/wlr_gtk_primary_selection.h: No such file or directory

**Comment by paleknight894** [comment]
wlr_gtk_primary_selection.h is missing in wlroots 0.14

**Comment by jubalh** [comment]
That's not very surprising when you see the status of the project (https://github.com/wizbright/waybox/issues/27) and consider how recent wlroots is.

**Comment by keithbowes** [comment]
I'm sorry for the late response.  I'm really bad at reading messages.  I'll try to do better.

Anyway, it works for me.  I replaced gtk-primary-selection with wp-primary-selection ages ago.

I even did a fresh clone to make sure my local copy didn't have anything that I didn't push to GitHub.  Yup, it compiles fine:
```
$ meson build
The Meson build system
Version: 0.60.3
Source dir: /home/keith/Elŝutoj/programs/wayland/waybox2
Build dir: /home/keith/Elŝutoj/programs/wayland/waybox2/build
Build type: native build
Project name: Waybox
Project version: 0.1.0
C compiler for the host machine: gcc (gcc 11.2.1 "gcc (Mageia 11.2.1-0.20220108.1.mga9) 11.2.1 20220108")
C linker for the host machine: gcc ld.bfd 2.37
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.7.3)
Run-time dependency wlroots found: YES 0.14.1
Run-time dependency wayland-server found: YES 1.20.0
Run-time dependency wayland-protocols found: YES 1.24
Run-time dependency xkbcommon found: YES 1.3.1
Program wayland-scanner found: YES 1.20.0 (/usr/bin/wayland-scanner)
Build targets in project: 45

Found ninja-1.10.2 at /usr/bin/ninja
keith@localhost ~/Elŝutoj/programs/wayland/waybox2 (master u=) 
$ ninja -C build
ninja: Entering directory `build'
[98/98] Linking target waybox/waybox
```

**Comment by keithbowes** [comment]
I'm closing.  If you still have this problem with the latest master branch, you can reopen.
